---
- name: Test configuration on EMR Master
  hosts: all
  become: true
  tasks:
    - name: Create test file
      file:
        path: /home/hadoop/awx_test_file.txt
        state: touch
        owner: hadoop
        mode: '0644'
