---
- name: Test Connectivity to EMR Master Node
  hosts: emr_master
  become: false
  gather_facts: false

  tasks:
    - name: Ping EMR Master Node
      ping:

    - name: Check SSH access to EMR
      ansible.builtin.command: hostname
      register: hostname_output

    - name: Print EMR Hostname
      debug:
        msg: "Connected to EMR master node. Hostname: {{ hostname_output.stdout }}"
